name: Build Protocol Translator
on: [push]
jobs:
    Build-Protocol-Translator:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Download Required Packages
              run: sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
            - run: ls -la
            - run: cd $GITHUB_WORKSPACE/WaccaProtocolTranslator
            - run: ls -la
            - run: sudo chmod +x autobuild.sh
            - name: Run Autobuild
              run: sudo sh autobuild.sh
            - uses: actions/upload-artifact@v3
              with:
                name: Protocol Translator Firmware
                path: $GITHUB_WORKSPACE/WaccaProtocolTranslator/artifacts/