name: Generate Production Files
on: [push]
jobs:
    Build-Touch-Panel:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Download Required Packages
              run: sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
            - name: Run Autobuild
              run: |
                sudo chmod +x autobuild.sh
                sudo sh autobuild.sh
              working-directory: ./WaccaTouchPanel
            - uses: actions/upload-artifact@v3
              with:
                name: Touch Panel Firmware
                path: ./WaccaTouchPanel/artifacts/
    Build-Protocol-Translator:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Download Required Packages
              run: sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
            - name: Run Autobuild
              run: |
                sudo chmod +x autobuild.sh
                sudo sh autobuild.sh
              working-directory: ./WaccaProtocolTranslator
            - uses: actions/upload-artifact@v3
              with:
                name: Protocol Translator Firmware
                path: ./WaccaProtocolTranslator/artifacts/