name: Generate Production Files
on: [push]
jobs:
    Build-Touch-Panel:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Download Required Packages
              run: sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
            - name: Run Autobuild
              run: |
                sudo chmod +x autobuild.sh
                sudo sh autobuild.sh
              working-directory: ./WaccaTouchPanel-firmware
            - uses: actions/upload-artifact@v3
              with:
                name: Touch Panel Firmware
                path: ./WaccaTouchPanel-firmware/artifacts/
    Build-Protocol-Translator:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Download Required Packages
              run: sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
            - name: Run Autobuild
              run: |
                sudo chmod +x autobuild.sh
                sudo sh autobuild.sh
              working-directory: ./WaccaProtocolTranslator-firmware
            - uses: actions/upload-artifact@v3
              with:
                name: Protocol Translator Firmware
                path: ./WaccaProtocolTranslator-firmware/artifacts/
    Generate-Protocol-Translator-PCB-Files:
        runs-on: ubuntu-latest
        container:
            image: setsoft/kicad_auto:ki6
        steps:
            - uses: actions/checkout@v2
            - name: Run KiBot
              run: |
                kibot -c kibot.yml -e WaccaProtocolTranslator-pcb/WaccaProtocolTranslator.kicad_sch -b WaccaProtocolTranslator-pcb/WaccaProtocolTranslator.kicad_pcb -d WaccaProtocolTranslator-pcb/ -s run_erc,run_drc -v \
                gerbers.gbr drills.gbr drills.drl pickandplace.csv bom.csv schematic.svg schematic.pdf board_black_top.svg model.step
            - uses: actions/upload-artifact@v2
              if: ${{success()}}
              with:
                name: Wacca Protocol Translator PCB Gerbers
                if-no-files-found: error
                path: |
                  WaccaProtocolTranslator-pcb/gerbers/**
                  !WaccaProtocolTranslator-pcb/**/*.ogv
                  !WaccaProtocolTranslator-pcb/**/*.log
            - uses: actions/upload-artifact@v2
              if: ${{success()}}
              with:
                name: Wacca Protocol Translator PCB Documentation
                if-no-files-found: error
                path: |
                  WaccaProtocolTranslator-pcb/docs/**
                  WaccaProtocolTranslator-pcb/img/**
                  WaccaProtocolTranslator-pcb/cad/**
                  !WaccaProtocolTranslator-pcb/**/*.ogv
                  !WaccaProtocolTranslator-pcb/**/*.log
